/**
 * Email Utility Functions
 * Uses mailto: links to open the user's email client with pre-filled content
 * Works in any environment including SharePoint
 */

/**
 * Open email client with pre-filled content
 * @param {string} to - Recipient email(s), comma separated
 * @param {string} subject - Email subject
 * @param {string} body - Email body (plain text)
 * @param {string} cc - CC recipients (optional)
 */
export const openEmailClient = (to, subject, body, cc = '') => {
  let mailtoUrl = `mailto:${encodeURIComponent(to)}`;
  mailtoUrl += `?subject=${encodeURIComponent(subject)}`;
  mailtoUrl += `&body=${encodeURIComponent(body)}`;
  if (cc) {
    mailtoUrl += `&cc=${encodeURIComponent(cc)}`;
  }

  // Open in new window to avoid navigation issues in SharePoint
  window.open(mailtoUrl, '_blank');
};

/**
 * Generate email body for a meeting summary
 * @param {Object} meeting - Meeting object with responses and isolations
 * @returns {string} Formatted email body
 */
export const generateMeetingSummaryEmail = (meeting) => {
  const date = meeting.date || new Date().toLocaleDateString();
  const attendees = meeting.attendees?.join(', ') || 'Not specified';

  let body = `LTI OMT MEETING SUMMARY\n`;
  body += `${'='.repeat(40)}\n\n`;
  body += `Date: ${date}\n`;
  body += `Attendees: ${attendees}\n\n`;

  // Statistics
  const responses = meeting.responses || {};
  const isolations = meeting.isolations || [];
  const totalReviewed = isolations.length || Object.keys(responses).length;

  body += `SUMMARY\n`;
  body += `${'-'.repeat(20)}\n`;
  body += `Total LTIs Reviewed: ${totalReviewed}\n`;

  // Count by risk level
  const riskCounts = { Critical: 0, High: 0, Medium: 0, Low: 0 };
  Object.values(responses).forEach(r => {
    const risk = r.riskLevel || r.risk || 'N/A';
    if (riskCounts[risk] !== undefined) riskCounts[risk]++;
  });

  body += `Critical Risk: ${riskCounts.Critical}\n`;
  body += `High Risk: ${riskCounts.High}\n`;
  body += `Medium Risk: ${riskCounts.Medium}\n`;
  body += `Low Risk: ${riskCounts.Low}\n\n`;

  // LTI Details
  body += `LTI DETAILS\n`;
  body += `${'-'.repeat(20)}\n`;

  if (isolations.length > 0) {
    isolations.forEach(iso => {
      const response = responses[iso.id] || {};
      body += `\n${iso.id}: ${iso.Title || iso.description || 'No description'}\n`;
      body += `  Risk Level: ${response.riskLevel || 'N/A'}\n`;
      body += `  MOC Required: ${response.mocRequired || 'N/A'}`;
      if (response.mocRequired === 'Yes' && response.mocNumber) {
        body += ` (${response.mocNumber})`;
      }
      body += `\n`;
      body += `  Action Required: ${response.actionRequired || 'N/A'}\n`;
      if (response.comments) {
        body += `  Comments: ${response.comments}\n`;
      }
    });
  } else {
    Object.entries(responses).forEach(([id, response]) => {
      body += `\n${id}\n`;
      body += `  Risk Level: ${response.riskLevel || response.risk || 'N/A'}\n`;
      body += `  MOC Required: ${response.mocRequired || 'N/A'}\n`;
      body += `  Action Required: ${response.actionRequired || 'N/A'}\n`;
      if (response.comments) {
        body += `  Comments: ${response.comments}\n`;
      }
    });
  }

  body += `\n${'='.repeat(40)}\n`;
  body += `Generated by LTI OMT Meeting System\n`;

  return body;
};

/**
 * Generate email body for Operations Manager report
 * @param {Array} ltis - Array of LTI data objects
 * @param {Object} stats - Dashboard statistics
 * @returns {string} Formatted email body
 */
export const generateOperationsManagerReportEmail = (ltis, stats) => {
  let body = `OPERATIONS MANAGER LTI STATUS REPORT\n`;
  body += `${'='.repeat(40)}\n\n`;
  body += `Report Date: ${new Date().toLocaleDateString()}\n\n`;

  body += `EXECUTIVE SUMMARY\n`;
  body += `${'-'.repeat(20)}\n`;
  body += `Total LTIs: ${stats.totalLTIs}\n`;
  body += `LTIs Over 6 Months (Requiring Review): ${stats.sixMonthsPlus}\n`;
  body += `Critical Risk: ${stats.criticalRisk}\n`;
  body += `High Risk: ${stats.highRisk}\n`;
  body += `MOCs Required: ${stats.mocRequired}\n`;
  body += `Equipment Issues: ${stats.equipmentIssues}\n`;
  body += `Urgent Actions Required: ${stats.urgentAction}\n\n`;

  // LTIs requiring attention (6+ months)
  if (stats.sixMonthsPlusLTIs && stats.sixMonthsPlusLTIs.length > 0) {
    body += `LTIs OVER 6 MONTHS - REQUIRING OPERATIONS MANAGER REVIEW\n`;
    body += `${'-'.repeat(45)}\n`;

    stats.sixMonthsPlusLTIs.forEach(lti => {
      body += `\n${lti.id}\n`;
      body += `  Description: ${lti.description}\n`;
      body += `  Age: ${lti.ageInfo?.display || 'Unknown'}\n`;
      body += `  Risk Level: ${lti.riskLevel}\n`;
      body += `  MOC Required: ${lti.mocRequired}`;
      if (lti.mocRequired === 'Yes') {
        body += ` - Status: ${lti.mocStatus || 'N/A'}`;
      }
      body += `\n`;
      body += `  Parts Required: ${lti.partsRequired}`;
      if (lti.partsRequired === 'Yes') {
        body += ` - Status: ${lti.partsStatus || 'N/A'}`;
      }
      body += `\n`;
      if (lti.comments) {
        body += `  Comments: ${lti.comments}\n`;
      }
    });
  }

  body += `\n${'='.repeat(40)}\n`;
  body += `WMS Manual Requirement: LTIs over 6 months require Operations Manager review every 6 months.\n`;
  body += `Generated by LTI OMT Meeting System\n`;

  return body;
};

/**
 * Generate email to notify attendees about meeting completion
 * @param {Object} meeting - Meeting object
 * @param {Array} attendees - Array of attendee names/emails
 * @returns {Object} { subject, body }
 */
export const generateAttendeeNotificationEmail = (meeting) => {
  const date = meeting.date || new Date().toLocaleDateString();
  const responses = meeting.responses || {};
  const isolations = meeting.isolations || [];
  const totalReviewed = isolations.length || Object.keys(responses).length;

  // Count action items
  let actionItemCount = 0;
  Object.values(responses).forEach(r => {
    if (r.actionItems && r.actionItems.length > 0) {
      actionItemCount += r.actionItems.length;
    }
  });

  // Count by action required
  const actionCounts = { Urgent: 0, 'Plan Work': 0, Monitor: 0 };
  Object.values(responses).forEach(r => {
    const action = r.actionRequired || 'N/A';
    if (actionCounts[action] !== undefined) actionCounts[action]++;
  });

  let body = `LTI OMT MEETING COMPLETED\n`;
  body += `${'='.repeat(40)}\n\n`;
  body += `The LTI OMT Meeting held on ${date} has been completed.\n\n`;

  body += `MEETING RESULTS\n`;
  body += `${'-'.repeat(20)}\n`;
  body += `Total LTIs Reviewed: ${totalReviewed}\n`;
  body += `Action Items Generated: ${actionItemCount}\n\n`;

  body += `ACTION REQUIRED BREAKDOWN\n`;
  body += `${'-'.repeat(25)}\n`;
  body += `Urgent: ${actionCounts.Urgent}\n`;
  body += `Plan Work: ${actionCounts['Plan Work']}\n`;
  body += `Monitor: ${actionCounts.Monitor}\n\n`;

  // List urgent items
  const urgentItems = [];
  if (isolations.length > 0) {
    isolations.forEach(iso => {
      const response = responses[iso.id];
      if (response?.actionRequired === 'Urgent') {
        urgentItems.push({
          id: iso.id,
          description: iso.Title || iso.description || 'No description',
          comments: response.comments
        });
      }
    });
  } else {
    Object.entries(responses).forEach(([id, response]) => {
      if (response.actionRequired === 'Urgent') {
        urgentItems.push({
          id,
          description: response.description || 'No description',
          comments: response.comments
        });
      }
    });
  }

  if (urgentItems.length > 0) {
    body += `URGENT ITEMS REQUIRING IMMEDIATE ATTENTION\n`;
    body += `${'-'.repeat(40)}\n`;
    urgentItems.forEach(item => {
      body += `\n- ${item.id}: ${item.description}\n`;
      if (item.comments) {
        body += `  Notes: ${item.comments}\n`;
      }
    });
    body += `\n`;
  }

  body += `Please review the full meeting summary in the LTI OMT Meeting System.\n\n`;
  body += `${'='.repeat(40)}\n`;
  body += `Generated by LTI OMT Meeting System\n`;

  const subject = `LTI OMT Meeting Completed - ${date} - ${totalReviewed} LTIs Reviewed`;

  return { subject, body };
};

/**
 * Generate JSON data for SharePoint save
 * @param {Object} meeting - Meeting object
 * @returns {string} JSON string of meeting data
 */
export const generateSharePointExportData = (meeting) => {
  return JSON.stringify(meeting, null, 2);
};

/**
 * Download data as a file (for SharePoint upload)
 * @param {string} content - File content
 * @param {string} filename - File name
 * @param {string} type - MIME type
 */
export const downloadAsFile = (content, filename, type = 'application/json') => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
